import LiffProvider from "@/providers/liff-provider";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import SocialMediaBar from "./components/SocialMediaBar/SocialMediaBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <LiffProvider>
        <body className={`flex flex-col h-screen`}>
          <main className="flex-grow overflow-y-auto">
            {children}
          </main>
          <SocialMediaBar />
        </body>
      </LiffProvider>
    </html>
  );
}
