name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: "18"
  FRONTEND_DIR: "."
  PNPM_VERSION: "9"

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          project-dir: ${{ env.FRONTEND_DIR }}

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          project-dir: ${{ env.FRONTEND_DIR }}

      - name: Run Lint
        run: pnpm run lint
        working-directory: ${{ env.FRONTEND_DIR }}

  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          project-dir: ${{ env.FRONTEND_DIR }}

      - name: Run Build
        run: pnpm run build
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ${{ env.FRONTEND_DIR }}/dist
